name: Simple CI Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: Create .env
        run: cp .env.example .env || echo ".env.example not found, continuing..."
        
      - name: Install dependencies
        run: composer install --no-interaction
        
      - name: Basic validation
        run: |
          php -v
          composer --version
          echo "✅ Basic setup completed"
