name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql

    - name: Create .env file
      run: |
        cp .env.example .env
        echo "APP_ENV=testing" >> .env
        echo "APP_KEY=base64:testkey123456789012345678901234567890" >> .env

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Validate configuration
      run: |
        php -v
        composer --version
        echo "✅ Environment setup completed successfully"
