
name: Laravel CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: " "
          MYSQL_DATABASE: ecommerce
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, bcmath
        coverage: none

    - name: Create .env file
      run: |
        cp .env.example .env
        echo "APP_ENV=testing" >> .env
        echo "APP_KEY=base64:testkey123456789012345678901234567890" >> .env
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=ecommerce" >> .env
        echo "DB_USERNAME=root" >> .env
        echo "DB_PASSWORD= " " >> .env

    - name: Wait for MySQL
      run: |
        sudo systemctl start mysql
        while ! mysqladmin ping -h"127.0.0.1" -u"root" -p"password" --silent; do
          sleep 1
        done

    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist --optimize-autoloader

    - name: Create database
      run: |
        mysql -h 127.0.0.1 -u root -ppassword -e "CREATE DATABASE IF NOT EXISTS ecommerce_test;"

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run tests
      run: ./vendor/bin/phpunit
